### ISSUE TITLE
Example of parameterization

### ISSUE THREAD

**Issue by moradza** [TinkerTools/poltype2#17]
Hi,

I am new to TinkerTools, I am trying to reproduce parameterization of ligand example. How much time it takes for parameterization to finish for lignad example. I got lots of warnings related to Open Babel. Is it detrimental to the results? And how long it takes to parameterize molecules with 50-100 atoms.

*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL file

*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL file

**Comment by bdw2292** [comment]
Hello and welcome,

Ah yeah I believe I tried to suppress those warnings at some point to no success. Might be worth another shot. 

Sadly I cannot give you an exact answer, it depends on many things such as the number of optimization cycles needed to converge geometry optimization, number of rotatable bonds, the number of basis functions for running each single point computation, the single point method being used and it’s scaling behavior with number of basis functions, how many single points are needed to sample dihedral angle energy surface, how many dihedral energy surfaces needed to be sampled, how many fragments for parameterizing torsion, how much RAM/ scratch space/ processors are allocated and how well those resources are used to parralelize many QM jobs at once. In the past molecules with about 100 atoms and giving >100GB ram still took almost a week. We’ve made some improvements in speed by replacing torsion QM geometry optimization with semi empirical optimizer but it’s complicated. I’ve added this running average of how much time total QM for each torsion fragment takes which tries to give a remaining ETA at torsion step but makes some assumptions like all fragments same number of rotatable bonds being used for sampling dihedral energy surface and all fragments same number of points per surface need to be sampled, all fragments roughly same atom size etc…

**Comment by bdw2292** [comment]
The warnings will not affect parameterization.

**Comment by moradza** [comment]
Thanks for the information! Make sense. I am just curious if there is any heuristic or empirical way to parameterize molecules?

**Comment by bdw2292** [comment]
I’m not sure I understand the question. It might be possible to get a closer ETA for a given molecule with poltype if at least one single point computation for each fragment and parent is done on a minimal size basis set first and if I could determine basis set size prior to running the actual full computation with default basis set assigned. In practice though parts of program related to torsion is done sequentially after QM for electrostatics is done so not all the information would be present at the beginning. Also the initial geometry optimization would be excluded from this estimate. I don’t recommend lowering basis sets or changing QM methods for actual paramterization though, the defaults are chosen because we think they are accurate whilst also trying to be computationally efficient without sacrificing that accuracy.

**Comment by moradza** [comment]
This answers my question. To be clear, I was thinking about a method to suggest parameters based on similarity to other molecules and without need to run QM

**Comment by bdw2292** [comment]
Yes that’s the main idea actually, if the parameters exist in a database they can be transferred, if not they need to be fit to QM. The trouble is for torsion, there are an enormous number of possible torsions (incomplete database). We also don’t define torsion transferability with just matching 4 atoms a-b-c-d to a database but rather also include information about neighboring atoms as well due to how sensitive the torsion energy barrier is to changes in nearby chemical environment. For electrostatic parameters, it is possible to also recycle some parameters for similar overlapping parts of the molecule. The procedure is roughly like during fitting, you fix parameters on the similar overlapping parts of the molecule then let electrostatic parameters in different part or molecule fit. This requires still the same amount of QM computation to get a potential grid around the molecule as if you had not intended to recycle parameters so it ends up not being any speed up in that case.
