### ISSUE TITLE
selectivity of tautomers for parameterization

### ISSUE THREAD

**Issue by blakemertz** [TinkerTools/poltype2#41]
Is there a way to guide poltype2 in choosing a subset of tautomers for small molecule parameterization? I have a small molecule with 4 tautomeric states, but upon visual inspection, State_1 and State_3 are incorrect based on my known chemistry. Here is what poltype2 has generated so far:

```
ls -ltr
total 736
-rwxr-xr-x 1 blake blake     48 Apr  2 15:04 poltype.ini
-rw-r--r-- 1 blake blake   5869 Apr  2 15:04 MDH-195.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:04 MDH-195.mol
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 conftest.mol
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 extendedconf.mol
-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 IonizationState_0.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 IonizationState_0.mol
-rw-r--r-- 1 blake blake   5979 Apr  2 15:05 IonizationState_1.sdf
-rw-r--r-- 1 blake blake   5371 Apr  2 15:05 IonizationState_1.mol
-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_0.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_0.mol
-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_1.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_1.mol
-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_2.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_2.mol
-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_3.sdf
-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_3.mol
-rw-r--r-- 1 blake blake   2746 Apr  2 15:05 MDH-195-opt_1_temp.com
-rw-r--r-- 1 blake blake   4317 Apr  2 15:05 MDH-195-opt_1.psi4
-rw-r--r-- 1 blake blake   2746 Apr  2 15:05 MDH-195-opt_1.com
-rw-r--r-- 1 blake blake    431 Apr  2 15:05 MDH-195-poltype.log
-rw-r--r-- 1 blake blake 587296 Apr  2 17:09 MDH-195-opt_1.log
-rw-r--r-- 1 blake blake     65 Apr  2 17:09 psi.136377.clean
```
Is there a way to flag poltype2 so that it will skip over parameterization of State_1 and State_3? Or can I simply delete/move the unwanted tautomers? Otherwise I will be wasting twice as many CPU cycles to carry out this parameterization. Thanks.

**Comment by pren** [comment]
Poltype2 default is not adding hydrogen to your input molecule, even though it generates the different states. Can you compare the opt input and your input molecule (sdf) to confirm?


From: blakemertz ***@***.***>
Date: Tuesday, April 2, 2024 at 5:16 PM
To: TinkerTools/poltype2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TinkerTools/poltype2] selectivity of tautomers for parameterization (Issue #41)

Is there a way to guide poltype2 in choosing a subset of tautomers for small molecule parameterization? I have a small molecule with 4 tautomeric states, but upon visual inspection, State_1 and State_3 are incorrect based on my known chemistry. Here is what poltype2 has generated so far:

ls -ltr

total 736

-rwxr-xr-x 1 blake blake     48 Apr  2 15:04 poltype.ini

-rw-r--r-- 1 blake blake   5869 Apr  2 15:04 MDH-195.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:04 MDH-195.mol

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 conftest.mol

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 extendedconf.mol

-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 IonizationState_0.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 IonizationState_0.mol

-rw-r--r-- 1 blake blake   5979 Apr  2 15:05 IonizationState_1.sdf

-rw-r--r-- 1 blake blake   5371 Apr  2 15:05 IonizationState_1.mol

-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_0.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_0.mol

-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_1.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_1.mol

-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_2.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_2.mol

-rw-r--r-- 1 blake blake   5869 Apr  2 15:05 TautomerState_3.sdf

-rw-r--r-- 1 blake blake   5270 Apr  2 15:05 TautomerState_3.mol

-rw-r--r-- 1 blake blake   2746 Apr  2 15:05 MDH-195-opt_1_temp.com

-rw-r--r-- 1 blake blake   4317 Apr  2 15:05 MDH-195-opt_1.psi4

-rw-r--r-- 1 blake blake   2746 Apr  2 15:05 MDH-195-opt_1.com

-rw-r--r-- 1 blake blake    431 Apr  2 15:05 MDH-195-poltype.log

-rw-r--r-- 1 blake blake 587296 Apr  2 17:09 MDH-195-opt_1.log

-rw-r--r-- 1 blake blake     65 Apr  2 17:09 psi.136377.clean

Is there a way to flag poltype2 so that it will skip over parameterization of State_1 and State_3? Or can I simply delete/move the unwanted tautomers? Otherwise I will be wasting twice as many CPU cycles to carry out this parameterization. Thanks.

**Comment by blakemertz** [comment]
@pren thanks for the quick response -- much appreciated. I confirmed that the optimization structure and my input structure are identical.

Can I get clarification on the purpose for generation of the ionization and tautomer molecules for parameterization if they are not being used? The advanced settings for poltype2 [documentation] (https://github.com/TinkerTools/poltype2/blob/master/README/README_HELP.MD) doesn't mention anything about either so I just want to make sure I understand the steps that are being carried out. Thanks.

**Comment by pren** [comment]
Poltype2 just generates the additional important protonation states so users are aware.  User can choose to run poltype on them if they want.

Thanks,
Pengyu

________________________________
