### ISSUE TITLE
Keyword "jobsatsametime" not working; Cannot allocate memory due to too many jobs started - using Psi4

### ISSUE THREAD

**Issue by jacekkozuch** [TinkerTools/poltype2#6]
Dear Poltype2 Team,

a parameterization of a larger molecule (penicillin G in this case) crashes, because "memory cannot be allocated" during the torsion sp QM calculations (using Psi4). I've noticed that this coincides with a long list of "job has not responded since 0.25 h" errors in the poltype.log file and a long list of jobs that have been started in parallel.

I tried to control this issue by using "jobsatsametime=1", but this keyword seems not work (or I am misunderstanding its purpose). Instead 4 jobs are running at the same time, I suppose due to the "coresperjob=2" as default.

Unfortunately, I cannot try if this also happens with Gaussian, since we only have G16 on the HPC.

I am putting the folder of my parameterization onto a drive and will share it in a bit. However, I already wanted to post this, in case this is an easy fix.

Thanks in advance!
Best,
Jacek

**Comment by bdw2292** [comment]
Hello,

Please try again with jobsatsametime=1 on new commit, it should work.

- Brandon

**Comment by jacekkozuch** [comment]
Thanks for the quick fix, Brandon! Worked!

Also noticed that I understood "numproc" and "maxmem" as per poltype run. However, I see that it is per submitted QM job. I think this misunderstanding caused the "cannot allocate memory" issue. Maybe you could specify this on the "Help Info" page. 

Best,
Jacek

**Comment by bdw2292** [comment]
No problem. Yes basically, maxmem and numproc are for the parent molecule,
then fragments will each get floor(resource/jobsatsametime).

**Comment by jacekkozuch** [comment]
This issue still happens during sp QM torsion calculations (opt calcs are fine!) in combination with "rotalltors". Removing "rotalltors" everything works fine; with "rotalltors" a lot of sp calculations are starting simultaneously

**Comment by bdw2292** [comment]
Hello,

Im having a hard time believing that, rotalltors has nothing to do with
behaviour of jobsatsametime. Could I see your input poltype.ini and poltype
output log file?

**Comment by jacekkozuch** [comment]
Hi Brandon,

attached the files. You'll see the errors and that several QM jobs are submitted, despite specifying just one to be submitted. Maybe that's some issue with SLURM submission. However, also there I also specified to only do one task. When "rotalltors" is deleted, I don't get these errors.

Thx for looking into it! 

Best,
Jacek

[PEN-poltype.log](https://github.com/TinkerTools/poltype2/files/8027762/PEN-poltype.log)
[poltype-ini.txt](https://github.com/TinkerTools/poltype2/files/8027766/poltype-ini.txt)

**Comment by bdw2292** [comment]
Hi Jacek,

What I suspect going on here is there was a previous poltype run and the
job was killed, so some QM output files are left unfinished in the
qm-torsion folder. Poltype has a rule that says if output file has not been
updated in the last X hours and its also not already finished, then it must
have crashed. This was added because sometimes QM will crash but output log
file will not change and also python subprocess library may not return a
signal that states an error has occured. I try to set the X value to be
reasonable depending on system size, for example, for fragments (smaller
than parent) I had opt and SP log files should be updated at least ever 15
minutes ( I just changed this to an hour). From what Im reading most of
them read "Error job not updated in X time" etc, which is normal except for
the SP job that was just submitted before that line. To me that indicates
that poltype is checking for updates in the output file faster than
submission system can send output file back or just update it. I have
adjusted the sleeptime variable to 5 seconds to try and see if that helps,
its also a keyword now in input file now. sleeptime controls how long
poltype waits after job submission before checking all files again etc..

- Brandon

**Comment by bdw2292** [comment]
To clarify, if poltype thinks file has not been updated fast enough, it
will think it has crashed, then move on to submit more jobs.

**Comment by jacekkozuch** [comment]
So, now the parameterization finished without any issues! Thanks!

**Comment by bdw2292** [comment]
;)
________________________________
