### ISSUE TITLE
Interpretation of OPENME outputs

### ISSUE THREAD

**Issue by blakemertz** [TinkerTools/poltype2#8]
Had a couple of questions on some fragment calculations -- working with Justin to parameterize fragments for the AMOEBA lipid library. 

1. Do all runs of poltype now produce an OPENME folder? I've had some runs finish without the folder, and didn't know if that was an incomplete run or if OPENME was only produced when there are torsion parameters that need to be checked.
2. Units of energy for the torsion fitting? For example, I have a torsion fitting plot with energy from -0.7 to 0.4, but no units are shown in the png file. The corresponding log file from psi4 (I have to check the poltype workflow, but I was looking at the single-point energy log file) was -346.99. Psi4 documentation states that these energies are in Hartrees, meaning my energy is about .... -210,000 kcal/mol. That's five orders of magnitude larger than what is reported in the torsion fitting plot.

I apologize if these are noob questions -- still moving from being an end-user of poltype to understanding how to troubleshoot each particular step in the workflow. Thanks.

**Comment by bdw2292** [comment]
Hello,

No worries. Yes, if final.key exists poltype always finish. The OPENME folder is just a collection of all fitting results from multipole, torsion and VdW in one place to make it easier to check fitting results. I added a note in the readme_help file. I have also added units to the torsion fit plot. The units are kcal/mol, however the energy arrays are normalized, so that is why the number seems so far off. Typically if there is a crash it will say in the -poltype.log file or in stdout. 

- Brandon

**Comment by blakemertz** [comment]
Thanks for the detailed explanation Brandon -- definitely helps. So essentially the scales on the VDW and torion energy plots can be shifted so that minimum are at 0 kcal/mol (I think for the plot I was looking at it was -0.7 to 0.4 kcal/mol). Good to know.

**Comment by bdw2292** [comment]
Ah okay I should clarify. The individual arrays for QM, MM1, MM2 are
normalized, so for the energy plot for example, minimum is 0. However the
torsion fit plot (plots QM-MM1 and the fit array to that target), if you
observe the minima is not 0 this is like because the QM and MM1 minima are
not exactly the same. I can renormalize the fit array and QM-MM1 array in
that plot to 0 after fitting to make it easier to compare differences on y
-axis.
